export const NEW_ROUTE = "NEW_ROUTE";

export const SET_NEW_ROUTES_ORDER = "SET_NEW_ROUTES_ORDER";

export const DELETE_ROUTE = "DELETE_ROUTE";

export const REPLACE_ROUTE = "REPLACE_ROUTE";

export const YANDEX_MAP_LOADED = "YANDEX_MAPS_LOADED";

export const SET_MAP_CENTER = "SET_MAP_CENTER";